package com.pharmacy.admin.dto;

public enum OrderStatus {
    DRAFT,
    CHECKOUT_STARTED,
    PRESCRIPTION_PENDING,
    PRESCRIPTION_APPROVED,
    PRESCRIPTION_REJECTED,
    PAYMENT_PENDING,
    PAID,
    PENDING_APPROVAL,   // paid — awaiting admin review
    PACKED,
    OUT_FOR_DELIVERY,
    DELIVERED,
    CUSTOMER_CANCELLED,
    ADMIN_CANCELLED,
    PAYMENT_FAILED,
    RETURN_REQUESTED,
    REFUND_INITIATED,
    REFUND_COMPLETED  // terminal state
}
